/**
 * create a object of Leaf and contain it's id and name
 */
var Leaf = {};
Leaf.id = 'leaf';
Leaf.series = 'leaf';
Leaf.libPath = "./packages/leaf/lib"


Leaf.width = 64.14;
Leaf.height = 40.65;
Leaf.pinWidth = 8;
Leaf.pinHeight = 8;
Leaf.name = "Leaf";
Leaf.kitName = "SensorKit For Leaf";
Leaf.nameEn = "Leaf";
Leaf.active = 'active';
Leaf.libs = [
];
Leaf.avalibleKits = [
    "SensorKit",
]
Leaf.pins = [{
        'id': 1,
        'name': 'A0',
        'x': 50.17,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 2,
        'name': 'A1',
        'x': 48.01,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 3,
        'name': 'A2',
        'x': 45.86,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 4,
        'name': 'A3',
        'x': 43.70,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 5,
        'name': 'A4',
        'x': 41.55,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 6,
        'name': 'A5',
        'x': 39.38,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 7,
        'name': 'A6',
        'x': 37.24,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 8,
        'name': 'A7',
        'x': 35.08,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 9,
        'name': 'A8',
        'x': 32.93,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 10,
        'name': 'A9',
        'x': 30.77,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain", "pwm"],
        'type': 'analog',
    },
    {
        'id': 11,
        'name': 'A10',
        'x': 28.62,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 12,
        'name': 'A11',
        'x': 26.46,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 13,
        'name': 'A12',
        'x': 24.31,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 14,
        'name': 'A13',
        'x': 22.15,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 15,
        'name': 'GND',
        'x': 20.01,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 16,
        'name': '3V3',
        'x': 17.85,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 17,
        'name': 'RST',
        'x': 15.69,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["RST"],
        'type': 'other',
    },
    {
        'id': 18,
        'name': 'DFU',
        'x': 13.54,
        'y': 2.94,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["DFU"],
        'type': 'other',
    },
    {
        'id': 19,
        'name': 'VIN',
        'x': 13.54,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["VIN"],
        'type': 'power',
    },
    {
        'id': 20,
        'name': '5V',
        'x': 15.69,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["5V"],
        'type': 'power',
    },
    {
        'id': 21,
        'name': '3V3',
        'x': 17.85,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 22,
        'name': 'GND',
        'x': 20.01,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 23,
        'name': 'D0',
        'x': 22.15,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 24,
        'name': 'D1',
        'x': 24.31,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 25,
        'name': 'D2',
        'x': 26.46,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 26,
        'name': 'D3',
        'x': 28.62,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 27,
        'name': 'D4',
        'x': 30.77,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 28,
        'name': 'D5',
        'x': 32.93,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout", "SCL"],
        'type': 'digital',
    },
    {
        'id': 29,
        'name': 'D6',
        'x': 35.08,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout", "SDA"],
        'type': 'digital',
    },
    {
        'id': 30,
        'name': 'D7',
        'x': 37.24,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 31,
        'name': 'D8',
        'x': 39.38,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 32,
        'name': 'D9',
        'x': 41.55,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 33,
        'name': 'D10',
        'x': 43.70,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 34,
        'name': 'D11',
        'x': 45.86,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 35,
        'name': 'D12',
        'x': 48.01,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
    {
        'id': 36,
        'name': 'D13',
        'x': 50.17,
        'y': 38.11,
        'width': Leaf.pinWidth,
        'height': Leaf.pinHeight,
        'isSource': false,
        'property': ["din", "dout"],
        'type': 'digital',
    },
]

Leaf.init = function() {
    // console.log('Leaf.init')
    Leaf.name = MSG.catLeaf;
    Leaf.kitName = MSG.catSensorKitForLeaf;
    // Leaf.description = MSG.leaf_description;
}