/**
 * create a object of RobotHat and contain it's id and name
 */
var RobotHat = {};
RobotHat.id = 'robothat';
RobotHat.kits = {}
RobotHat.series = "raspberrypi";
RobotHat.nameEn = "RobotHat";
RobotHat.type = "raspberrypi";
RobotHat.libPath = "./packages/robothat/lib"

RobotHat.functions = [
    "remote",
    "routing",
    "bluetooth",
    "play",
]

RobotHat.libs = [
    'robothat==v0.2',
];

RobotHat.width = 87;
RobotHat.height = 58;
RobotHat.pinWidth = 8;
RobotHat.pinHeight = 8;
RobotHat.examples = {};
RobotHat.examplesHasKit = {};
RobotHat.tutorials = {};
RobotHat.tutorialsHasKit = {};

RobotHat.VOLTAGE_LEVEL_THRESHOLD = 1.5;
RobotHat.pwmReference = 4095;
RobotHat.adcReference = 4095;


RobotHat.routingOffset = {
    x: 0.7,
    y: 2.6,
}

RobotHat.pins = [
    // 1-1
    {
        'id': 1,
        'name': 'GND',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 10.51 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 2,
        'name': 'GND',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 10.51 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 3,
        'name': 'GND',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 10.51 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 4,
        'name': 'GND',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 10.51 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    // 1-2
    {
        'id': 5,
        'name': '5V',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 13.10 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["5V"],
        'type': 'power',
    },
    {
        'id': 6,
        'name': '5V',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 13.10 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["5V"],
        'type': 'power',
    },
    {
        'id': 7,
        'name': '5V',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 13.10 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["5V"],
        'type': 'power',
    },
    {
        'id': 8,
        'name': '5V',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 13.10 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["5V"],
        'type': 'power',
    },
    // 1-3
    {
        'id': 9,
        'name': 'P0',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 15.69 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 10,
        'name': 'P1',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 15.69 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 11,
        'name': 'P2',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 15.69 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 12,
        'name': 'P3',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 15.69 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 2-1
    {
        'id': 13,
        'name': 'GND',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 19.68 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 14,
        'name': 'GND',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 19.68 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 15,
        'name': 'GND',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 19.68 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 16,
        'name': 'GND',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 19.68 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    // 2-2
    {
        'id': 17,
        'name': '3V3',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 22.27 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 18,
        'name': '3V3',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 22.27 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 19,
        'name': '3V3',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 22.27 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 20,
        'name': '3V3',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 22.27 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    // 2-3
    {
        'id': 21,
        'name': 'P0',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 24.86 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 22,
        'name': 'P1',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 24.86 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 23,
        'name': 'P2',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 24.86 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    {
        'id': 24,
        'name': 'P3',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 24.86 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["ain"],
        'type': 'analog',
    },
    // 3-1
    {
        'id': 25,
        'name': 'GND',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 28.85 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 26,
        'name': 'GND',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 28.85 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 27,
        'name': 'GND',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 28.85 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 28,
        'name': 'GND',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 28.85 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    // 3-2
    {
        'id': 29,
        'name': '3V3',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 31.44 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 30,
        'name': '3V3',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 31.44 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 31,
        'name': '3V3',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 31.44 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 32,
        'name': '3V3',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 31.44 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    // 3-3
    {
        'id': 33,
        'name': 'D0',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 34.03 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["din"],
        'type': 'digital',
    },
    {
        'id': 34,
        'name': 'D1',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 34.03 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["din"],
        'type': 'digital',
    },
    {
        'id': 35,
        'name': 'D2',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 34.03 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["din"],
        'type': 'digital',
    },
    {
        'id': 36,
        'name': 'D3',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 34.03 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["din"],
        'type': 'digital',
    },
    // 4-1
    {
        'id': 37,
        'name': 'GND',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 39.53 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'grpund',
    },
    {
        'id': 38,
        'name': '3V3',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 39.53 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 39,
        'name': 'SDA',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 39.53 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["SDA"],
        'type': 'com',
    },
    {
        'id': 40,
        'name': 'SCL',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 39.53 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["SCL"],
        'type': 'com',
    },
    // 4-2
    {
        'id': 41,
        'name': 'GND',
        'x': 36.27 + RobotHat.routingOffset.x,
        'y': 42.12 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["GND"],
        'type': 'ground',
    },
    {
        'id': 42,
        'name': '3V3',
        'x': 38.80 + RobotHat.routingOffset.x,
        'y': 42.12 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["3V3"],
        'type': 'power',
    },
    {
        'id': 43,
        'name': 'SDA',
        'x': 41.33 + RobotHat.routingOffset.x,
        'y': 42.12 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["SDA"],
        'type': 'com',
    },
    {
        'id': 44,
        'name': 'SCL',
        'x': 43.86 + RobotHat.routingOffset.x,
        'y': 42.12 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["SCL"],
        'type': 'com',
    },

]

RobotHat.init = function() {
    RobotHat.name = MSG.catRobothat;
    RobotHat.description = MSG.robothat_description;
}