/**
 * create a object of RobotHat and contain it's id and name
 */
var RobotHat = {};
RobotHat.id = 'robothat';
RobotHat.kits = {}
RobotHat.series = "raspberrypi";
RobotHat.nameEn = "RobotHat";
RobotHat.type = "raspberrypi";
RobotHat.libPath = "./packages/robothat/lib"

RobotHat.functions = [
    "remote",
    "routing",
    "bluetooth",
    "play",
]

RobotHat.libs = [
    'robothat==v0.2',
];

RobotHat.width = 87;
RobotHat.height = 58;
RobotHat.pinWidth = 8;
RobotHat.pinHeight = 8;
RobotHat.examples = {};
RobotHat.examplesHasKit = {};
RobotHat.tutorials = {};
RobotHat.tutorialsHasKit = {};

RobotHat.VOLTAGE_LEVEL_THRESHOLD = 1.5;
RobotHat.pwmReference = 4095;
RobotHat.adcReference = 4095;


RobotHat.routingOffset = {
    x: 0.7,
    y: 2.6,
}

RobotHat.pins = [
    // 1-1
    {
        'id': 1,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 9.30 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 2,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 9.30 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 3,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 9.30 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 4,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 9.30 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 1-2

    {
        'id': 5,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 9.98 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 6,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 9.98 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 7,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 9.98 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 8,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 9.98 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 1-3

    {
        'id': 9,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 10.65 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 10,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 10.65 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 11,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 10.65 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 12,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 10.65 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 2-1

    {
        'id': 13,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 14.78 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 14,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 14.78 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 15,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 14.78 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 16,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 14.78 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 2-2

    {
        'id': 17,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 15.45 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 18,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 15.45 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 19,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 15.45 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 20,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 15.45 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 2-3

    {
        'id': 21,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 16.13 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 22,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 16.13 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 23,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 16.13 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 24,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 16.13 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 3-1

    {
        'id': 25,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 20.25 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 26,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 20.25 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 27,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 20.25 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 28,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 20.25 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 3-2

    {
        'id': 29,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 20.93 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 30,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 20.93 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 31,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 20.93 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 32,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 20.93 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 3-3
    {
        'id': 33,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 34,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 35,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 36,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 4-1
    {
        'id': 37,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 38,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 39,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 40,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    // 4-2
    {
        'id': 41,
        'name': 'P0',
        'x': 28.09 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 42,
        'name': 'P1',
        'x': 28.77 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 43,
        'name': 'P2',
        'x': 29.45 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
    {
        'id': 44,
        'name': 'P3',
        'x': 30.12 + RobotHat.routingOffset.x,
        'y': 21.60 + RobotHat.routingOffset.y,
        'width': RobotHat.pinWidth,
        'height': RobotHat.pinHeight,
        'isSource': false,
        'property': ["pwm"],
        'type': 'pwm',
    },
]

RobotHat.init = function() {
    RobotHat.name = MSG.catRobothat;
    RobotHat.description = MSG.robothat_description;
}